spring.application.name=demo
spring.datasource.url=jdbc:sqlite:demo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.thymeleaf.cache=false
spring.sql.init.mode=always
